export type Locale = 'en' | 'bn';

export const locales: { id: Locale; label: string; native: string }[] = [
  { id: 'en', label: 'English', native: 'English' },
  { id: 'bn', label: 'Bangla', native: 'বাংলা' },
];

type Dict = Record<string, string>;

export const translations: Record<Locale, Dict> = {
  en: {
    'nav.features': 'Features',
    'nav.workflow': 'Workflow',
    'nav.pricing': 'Pricing',
    'nav.faq': 'FAQ',
    'nav.signin': 'Sign in',
    'nav.startFree': 'Start Free',
    'hero.badge': 'Now with AI Document Assistant',
    'hero.title1': 'Create Professional Documents',
    'hero.title2': 'with AI',
    'hero.subtitle':
      'Generate beautiful presentations, resumes, reports, proposals and business plans in seconds.',
    'hero.startFree': 'Start Free',
    'hero.watchDemo': 'Watch Demo',
    'hero.noCard': 'No credit card required',
    'hero.trusted': 'Trusted by teams at',
    'features.eyebrow': 'Document types',
    'features.title': 'Every document you need, generated by AI',
    'features.subtitle':
      'From pitch decks to research papers — DocumentOS AI handles the structure, copy, and design so you can ship faster.',
    'workflow.eyebrow': 'AI Workflow',
    'workflow.title': 'From idea to polished document in four steps',
    'workflow.step1.title': 'Describe',
    'workflow.step1.desc': 'Tell the AI what you need in plain language — audience, tone, length.',
    'workflow.step2.title': 'Generate',
    'workflow.step2.desc': 'AI drafts the full document — structure, copy, charts, and design.',
    'workflow.step3.title': 'Refine',
    'workflow.step3.desc': 'Tweak in the visual editor or ask the AI assistant to rewrite sections.',
    'workflow.step4.title': 'Export',
    'workflow.step4.desc': 'Export to PDF, PPTX, or DOCX — or present directly from the editor.',
    'pricing.eyebrow': 'Pricing',
    'pricing.title': 'Simple, transparent pricing',
    'pricing.subtitle': 'Start free. Upgrade when you need more power.',
    'pricing.popular': 'Most popular',
    'pricing.current': 'Current',
    'pricing.forever': 'forever',
    'pricing.month': 'month',
    'testimonials.eyebrow': 'Testimonials',
    'testimonials.title': 'Loved by creators and teams',
    'faq.eyebrow': 'FAQ',
    'faq.title': 'Frequently asked questions',
    'cta.title': 'Start creating professional documents today',
    'cta.subtitle':
      'Join thousands of professionals using DocumentOS AI to ship beautiful documents in seconds.',
    'cta.startFree': 'Start Free',
    'cta.viewDemo': 'View Demo Dashboard',
    'footer.tagline':
      'Create presentations, CVs, reports, proposals and professional documents with AI.',
    'footer.rights': '© 2026 DocumentOS AI. All rights reserved.',
    'footer.built': 'Built with AI for professionals.',
    'footer.product': 'Product',
    'footer.company': 'Company',
    'footer.resources': 'Resources',
    'footer.legal': 'Legal',
    'featuresPage.title': 'Features',
    'featuresPage.subtitle':
      'Everything you need to create, edit, and ship professional documents with AI.',
    'featuresPage.ai.title': 'AI Document Generation',
    'featuresPage.ai.desc':
      'Describe what you want in plain language and get a complete, editable document in seconds.',
    'featuresPage.editor.title': 'Visual Editor',
    'featuresPage.editor.desc':
      'A Figma-like canvas with draggable elements, alignment guides, and a powerful properties panel.',
    'featuresPage.assistant.title': 'AI Assistant',
    'featuresPage.assistant.desc':
      'Rewrite, expand, summarize, translate, generate charts, and improve design with one click.',
    'featuresPage.brand.title': 'Brand Kit',
    'featuresPage.brand.desc':
      'Apply your logo, colors, and fonts across every document automatically.',
    'featuresPage.templates.title': 'Template Marketplace',
    'featuresPage.templates.desc':
      'Start from hundreds of professionally designed templates for any document type.',
    'featuresPage.collab.title': 'Real-time Collaboration',
    'featuresPage.collab.desc':
      'Work together with your team in real time with comments and granular permissions.',
    'featuresPage.export.title': 'Export Anywhere',
    'featuresPage.export.desc':
      'Export to PDF, PPTX, DOCX, and PNG — or present full-screen directly from the editor.',
    'featuresPage.ctaTitle': 'Ready to create your first document?',
    'featuresPage.ctaSubtitle':
      'Start free and upgrade when you need more power.',
    'featuresPage.ctaButton': 'Start Free',
    'common.back': 'Back to home',
  },
  bn: {
    'nav.features': 'ফিচার',
    'nav.workflow': 'ওয়ার্কফ্লো',
    'nav.pricing': 'মূল্য',
    'nav.faq': 'প্রশ্ন',
    'nav.signin': 'সাইন ইন',
    'nav.startFree': 'ফ্রি শুরু করুন',
    'hero.badge': 'এখন AI ডকুমেন্ট অ্যাসিস্ট্যান্ট সহ',
    'hero.title1': 'AI দিয়ে পেশাদার ডকুমেন্ট তৈরি করুন',
    'hero.title2': '',
    'hero.subtitle':
      'কয়েক সেকেন্ডে সুন্দর প্রেজেন্টেশন, রিজিউমি, রিপোর্ট, প্রস্তাব এবং বিজনেস প্ল্যান তৈরি করুন।',
    'hero.startFree': 'ফ্রি শুরু করুন',
    'hero.watchDemo': 'ডেমো দেখুন',
    'hero.noCard': 'কোনো ক্রেডিট কার্ড লাগবে না',
    'hero.trusted': 'যেসব প্রতিষ্ঠানের বিশ্বাস',
    'features.eyebrow': 'ডকুমেন্টের ধরন',
    'features.title': 'আপনার প্রয়োজনীয় সব ডকুমেন্ট, AI দিয়ে তৈরি',
    'features.subtitle':
      'পিচ ডেক থেকে রিসার্চ পেপার — DocumentOS AI কাঠামো, লেখা এবং ডিজাইন সামলায় যাতে আপনি দ্রুত কাজ শেষ করতে পারেন।',
    'workflow.eyebrow': 'AI ওয়ার্কফ্লো',
    'workflow.title': 'চিন্তা থেকে পরিপূর্ণ ডকুমেন্ট মাত্র চার ধাপে',
    'workflow.step1.title': 'বর্ণনা করুন',
    'workflow.step1.desc': 'সাধারণ ভাষায় AI-কে বলুন আপনি কী চান — শ্রোতা, ধরন, দৈর্ঘ্য।',
    'workflow.step2.title': 'তৈরি করুন',
    'workflow.step2.desc': 'AI সম্পূর্ণ ডকুমেন্ট তৈরি করে — কাঠামো, লেখা, চার্ট এবং ডিজাইন।',
    'workflow.step3.title': 'পরিমার্জন',
    'workflow.step3.desc': 'ভিজ্যুয়াল এডিটরে পরিবর্তন করুন বা AI অ্যাসিস্ট্যান্টকে বলুন আবার লিখতে।',
    'workflow.step4.title': 'রপ্তানি',
    'workflow.step4.desc': 'PDF, PPTX বা DOCX-এ রপ্তানি করুন — বা সরাসরি এডিটর থেকে উপস্থাপন করুন।',
    'pricing.eyebrow': 'মূল্য',
    'pricing.title': 'সহজ, স্বচ্ছ মূল্য',
    'pricing.subtitle': 'ফ্রি শুরু করুন। প্রয়োজনে আপগ্রেড করুন।',
    'pricing.popular': 'সবচেয়ে জনপ্রিয়',
    'pricing.current': 'বর্তমান',
    'pricing.forever': 'চিরকাল',
    'pricing.month': 'মাস',
    'testimonials.eyebrow': 'প্রশংসা',
    'testimonials.title': 'ক্রিয়েটর ও টিমের ভালোবাসা পেয়েছে',
    'faq.eyebrow': 'প্রশ্ন',
    'faq.title': 'সাধারণ জিজ্ঞাসা',
    'cta.title': 'আজই পেশাদার ডকুমেন্ট তৈরি শুরু করুন',
    'cta.subtitle':
      'হাজার হাজার পেশাদার DocumentOS AI ব্যবহার করে কয়েক সেকেন্ডে সুন্দর ডকুমেন্ট তৈরি করছেন।',
    'cta.startFree': 'ফ্রি শুরু করুন',
    'cta.viewDemo': 'ডেমো ড্যাশবোর্ড দেখুন',
    'footer.tagline':
      'AI দিয়ে প্রেজেন্টেশন, সিভি, রিপোর্ট, প্রস্তাব এবং পেশাদার ডকুমেন্ট তৈরি করুন।',
    'footer.rights': '© ২০২৬ DocumentOS AI. সর্বস্বত্ব সংরক্ষিত।',
    'footer.built': 'পেশাদারদের জন্য AI দিয়ে তৈরি।',
    'footer.product': 'প্রোডাক্ট',
    'footer.company': 'কোম্পানি',
    'footer.resources': 'রিসোর্স',
    'footer.legal': 'আইনি',
    'featuresPage.title': 'ফিচার',
    'featuresPage.subtitle':
      'AI দিয়ে পেশাদার ডকুমেন্ট তৈরি, সম্পাদনা এবং শেয়ার করতে যা যা দরকার।',
    'featuresPage.ai.title': 'AI ডকুমেন্ট জেনারেশন',
    'featuresPage.ai.desc':
      'সাধারণ ভাষায় বর্ণনা করুন এবং কয়েক সেকেন্ডে সম্পূর্ণ সম্পাদনাযোগ্য ডকুমেন্ট পান।',
    'featuresPage.editor.title': 'ভিজ্যুয়াল এডিটর',
    'featuresPage.editor.desc':
      'Figma-এর মতো ক্যানভাস, টেনে আনা উপাদান, অ্যালাইনমেন্ট গাইড এবং শক্তিশালী প্রপার্টিজ প্যানেল।',
    'featuresPage.assistant.title': 'AI অ্যাসিস্ট্যান্ট',
    'featuresPage.assistant.desc':
      'এক ক্লিকে পুনরায় লেখা, প্রসারণ, সারাংশ, অনুবাদ, চার্ট তৈরি এবং ডিজাইন উন্নত করুন।',
    'featuresPage.brand.title': 'ব্র্যান্ড কিট',
    'featuresPage.brand.desc':
      'আপনার লোগো, রঙ এবং ফন্ট স্বয়ংক্রিয়ভাবে সব ডকুমেন্টে প্রয়োগ করুন।',
    'featuresPage.templates.title': 'টেমপ্লেট মার্কেটপ্লেস',
    'featuresPage.templates.desc':
      'যেকোনো ডকুমেন্টের ধরনের জন্য শত শত পেশাদার টেমপ্লেট থেকে শুরু করুন।',
    'featuresPage.collab.title': 'রিয়েল-টাইম সহযোগিতা',
    'featuresPage.collab.desc':
      'আপনার টিমের সাথে রিয়েল টাইমে একসাথে কাজ করুন, মন্তব্য এবং অনুমতি সহ।',
    'featuresPage.export.title': 'যেকোনো জায়গায় রপ্তানি',
    'featuresPage.export.desc':
      'PDF, PPTX, DOCX এবং PNG-এ রপ্তানি করুন — বা সরাসরি এডিটর থেকে ফুল-স্ক্রিনে উপস্থাপন করুন।',
    'featuresPage.ctaTitle': 'আপনার প্রথম ডকুমেন্ট তৈরি করতে প্রস্তুত?',
    'featuresPage.ctaSubtitle': 'ফ্রি শুরু করুন এবং প্রয়োজনে আপগ্রেড করুন।',
    'featuresPage.ctaButton': 'ফ্রি শুরু করুন',
    'common.back': 'হোমে ফিরে যান',
  },
};
