import {
  ActivityPoint,
  BrandKit,
  DocType,
  DocTypeMeta,
  DocumentItem,
  InvoiceItem,
  PlanTier,
  StorageBreakdown,
  Template,
  User,
} from '@/types';

export const docTypes: DocTypeMeta[] = [
  {
    id: 'presentation',
    label: 'Presentation',
    icon: 'Presentation',
    description: 'Slides that captivate any audience',
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'resume',
    label: 'Resume / CV',
    icon: 'FileUser',
    description: 'Land your next role with a standout CV',
    gradient: 'from-emerald-500 to-teal-500',
  },
  {
    id: 'report',
    label: 'Report',
    icon: 'FileText',
    description: 'Data-rich reports in minutes',
    gradient: 'from-amber-500 to-orange-500',
  },
  {
    id: 'proposal',
    label: 'Proposal',
    icon: 'FileCheck',
    description: 'Win deals with persuasive proposals',
    gradient: 'from-rose-500 to-pink-500',
  },
  {
    id: 'business-plan',
    label: 'Business Plan',
    icon: 'Briefcase',
    description: 'Investor-ready plans with projections',
    gradient: 'from-indigo-500 to-blue-500',
  },
  {
    id: 'invoice',
    label: 'Invoice',
    icon: 'Receipt',
    description: 'Clean, branded invoices instantly',
    gradient: 'from-violet-500 to-purple-500',
  },
  {
    id: 'certificate',
    label: 'Certificate',
    icon: 'Award',
    description: 'Elegant certificates for any occasion',
    gradient: 'from-yellow-500 to-amber-500',
  },
  {
    id: 'research-paper',
    label: 'Research Paper',
    icon: 'GraduationCap',
    description: 'Academic formatting done right',
    gradient: 'from-sky-500 to-indigo-500',
  },
];

export const docTypeLabel: Record<DocType, string> = {
  presentation: 'Presentation',
  resume: 'Resume',
  report: 'Report',
  proposal: 'Proposal',
  'business-plan': 'Business Plan',
  invoice: 'Invoice',
  certificate: 'Certificate',
  'research-paper': 'Research Paper',
};

export const currentUser: User = {
  id: 'u_1',
  name: 'Alex Morgan',
  email: 'alex.morgan@documentos.ai',
  avatar: 'https://i.pravatar.cc/150?img=12',
  plan: 'Pro',
  credits: 1240,
  maxCredits: 2000,
  storage: 3.4,
  maxStorage: 10,
};

export const recentDocuments: DocumentItem[] = [
  {
    id: 'd1',
    title: 'Q4 Investor Pitch Deck',
    type: 'presentation',
    thumbnail: 'gradient-1',
    updatedAt: '2026-07-17T10:24:00Z',
    createdAt: '2026-07-10T09:00:00Z',
    pages: 14,
    starred: true,
    shared: true,
    owner: 'You',
    status: 'published',
  },
  {
    id: 'd2',
    title: 'Senior Product Designer CV',
    type: 'resume',
    thumbnail: 'gradient-2',
    updatedAt: '2026-07-16T14:30:00Z',
    createdAt: '2026-07-12T11:00:00Z',
    pages: 2,
    starred: false,
    shared: false,
    owner: 'You',
    status: 'draft',
  },
  {
    id: 'd3',
    title: 'Annual Sustainability Report',
    type: 'report',
    thumbnail: 'gradient-3',
    updatedAt: '2026-07-15T08:15:00Z',
    createdAt: '2026-06-28T08:00:00Z',
    pages: 38,
    starred: true,
    shared: true,
    owner: 'You',
    status: 'published',
  },
  {
    id: 'd4',
    title: 'Acme Corp — Software Proposal',
    type: 'proposal',
    thumbnail: 'gradient-4',
    updatedAt: '2026-07-14T16:45:00Z',
    createdAt: '2026-07-01T13:00:00Z',
    pages: 22,
    starred: false,
    shared: true,
    owner: 'You',
    status: 'draft',
  },
  {
    id: 'd5',
    title: 'Helio — 2026 Business Plan',
    type: 'business-plan',
    thumbnail: 'gradient-5',
    updatedAt: '2026-07-13T12:00:00Z',
    createdAt: '2026-06-20T10:00:00Z',
    pages: 31,
    starred: false,
    shared: false,
    owner: 'You',
    status: 'published',
  },
  {
    id: 'd6',
    title: 'Consulting Invoice #1042',
    type: 'invoice',
    thumbnail: 'gradient-6',
    updatedAt: '2026-07-11T09:30:00Z',
    createdAt: '2026-07-11T09:30:00Z',
    pages: 1,
    starred: false,
    shared: false,
    owner: 'You',
    status: 'published',
  },
  {
    id: 'd7',
    title: 'Course Completion Certificate',
    type: 'certificate',
    thumbnail: 'gradient-7',
    updatedAt: '2026-07-09T18:00:00Z',
    createdAt: '2026-07-09T18:00:00Z',
    pages: 1,
    starred: true,
    shared: false,
    owner: 'You',
    status: 'published',
  },
  {
    id: 'd8',
    title: 'Neural Networks — Research Paper',
    type: 'research-paper',
    thumbnail: 'gradient-8',
    updatedAt: '2026-07-08T07:20:00Z',
    createdAt: '2026-06-15T07:00:00Z',
    pages: 12,
    starred: false,
    shared: true,
    owner: 'You',
    status: 'draft',
  },
];

export const templates: Template[] = [
  {
    id: 't1',
    name: 'Aurora Pitch Deck',
    category: 'Pitch Decks',
    type: 'presentation',
    thumbnail: 'gradient-1',
    author: 'DocumentOS Studio',
    downloads: 12400,
    rating: 4.9,
    pro: false,
    colors: ['#2563EB', '#7C3AED', '#0EA5E9'],
  },
  {
    id: 't2',
    name: 'Minimal Resume Pro',
    category: 'Resumes',
    type: 'resume',
    thumbnail: 'gradient-2',
    author: 'CV Lab',
    downloads: 28900,
    rating: 4.8,
    pro: false,
    colors: ['#059669', '#0D9488', '#10B981'],
  },
  {
    id: 't3',
    name: 'Executive Report',
    category: 'Reports',
    type: 'report',
    thumbnail: 'gradient-3',
    author: 'Report Forge',
    downloads: 8700,
    rating: 4.7,
    pro: true,
    colors: ['#F59E0B', '#F97316', '#EA580C'],
  },
  {
    id: 't4',
    name: 'Sales Proposal Pro',
    category: 'Proposals',
    type: 'proposal',
    thumbnail: 'gradient-4',
    author: 'Deal Desk',
    downloads: 6200,
    rating: 4.6,
    pro: true,
    colors: ['#E11D48', '#EC4899', '#F43F5E'],
  },
  {
    id: 't5',
    name: 'Startup Business Plan',
    category: 'Business Plans',
    type: 'business-plan',
    thumbnail: 'gradient-5',
    author: 'Venture Kit',
    downloads: 9800,
    rating: 4.9,
    pro: true,
    colors: ['#6366F1', '#3B82F6', '#0EA5E9'],
  },
  {
    id: 't6',
    name: 'Clean Invoice',
    category: 'Invoices',
    type: 'invoice',
    thumbnail: 'gradient-6',
    author: 'Ledger',
    downloads: 15200,
    rating: 4.5,
    pro: false,
    colors: ['#8B5CF6', '#A855F7', '#6D28D9'],
  },
  {
    id: 't7',
    name: 'Gold Certificate',
    category: 'Certificates',
    type: 'certificate',
    thumbnail: 'gradient-7',
    author: 'Honor Studio',
    downloads: 5400,
    rating: 4.8,
    pro: false,
    colors: ['#EAB308', '#F59E0B', '#D97706'],
  },
  {
    id: 't8',
    name: 'Academic Research Paper',
    category: 'Research',
    type: 'research-paper',
    thumbnail: 'gradient-8',
    author: 'Scholar',
    downloads: 3200,
    rating: 4.7,
    pro: true,
    colors: ['#0EA5E9', '#6366F1', '#3B82F6'],
  },
  {
    id: 't9',
    name: 'Nova Product Launch',
    category: 'Pitch Decks',
    type: 'presentation',
    thumbnail: 'gradient-1',
    author: 'DocumentOS Studio',
    downloads: 7600,
    rating: 4.8,
    pro: true,
    colors: ['#2563EB', '#0EA5E9', '#06B6D4'],
  },
  {
    id: 't10',
    name: 'Creative Portfolio CV',
    category: 'Resumes',
    type: 'resume',
    thumbnail: 'gradient-2',
    author: 'CV Lab',
    downloads: 11200,
    rating: 4.9,
    pro: true,
    colors: ['#10B981', '#14B8A6', '#06B6D4'],
  },
  {
    id: 't11',
    name: 'Quarterly Business Review',
    category: 'Reports',
    type: 'report',
    thumbnail: 'gradient-3',
    author: 'Report Forge',
    downloads: 4900,
    rating: 4.6,
    pro: true,
    colors: ['#F97316', '#F59E0B', '#EF4444'],
  },
  {
    id: 't12',
    name: 'Partnership Proposal',
    category: 'Proposals',
    type: 'proposal',
    thumbnail: 'gradient-4',
    author: 'Deal Desk',
    downloads: 3800,
    rating: 4.5,
    pro: false,
    colors: ['#EC4899', '#F43F5E', '#E11D48'],
  },
];

export const templateCategories = [
  'All',
  'Pitch Decks',
  'Resumes',
  'Reports',
  'Proposals',
  'Business Plans',
  'Invoices',
  'Certificates',
  'Research',
];

export const examplePrompts = [
  'Create a 10-slide pitch deck for an AI-powered fitness app targeting Series A investors',
  'Generate a senior product manager resume highlighting 8 years of experience',
  'Build a Q3 marketing report with campaign performance and ROI analysis',
  'Draft a software development proposal for a fintech client with timeline and pricing',
  'Write a business plan for a sustainable coffee subscription startup',
];

export const aiSuggestions = [
  'Make it more concise',
  'Add a financial projections slide',
  'Improve the design with better contrast',
  'Suggest a stronger headline',
  'Translate to Spanish',
  'Generate a matching chart',
];

export const monthlyActivity: ActivityPoint[] = [
  { label: 'Jan', documents: 12, ai: 340 },
  { label: 'Feb', documents: 18, ai: 520 },
  { label: 'Mar', documents: 15, ai: 480 },
  { label: 'Apr', documents: 24, ai: 710 },
  { label: 'May', documents: 28, ai: 980 },
  { label: 'Jun', documents: 32, ai: 1120 },
  { label: 'Jul', documents: 26, ai: 890 },
];

export const storageBreakdown: StorageBreakdown[] = [
  { label: 'Presentations', value: 1.4, color: 'hsl(var(--chart-1))' },
  { label: 'Reports', value: 0.9, color: 'hsl(var(--chart-2))' },
  { label: 'Resumes', value: 0.4, color: 'hsl(var(--chart-3))' },
  { label: 'Other', value: 0.7, color: 'hsl(var(--chart-4))' },
];

export const planTiers: PlanTier[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    period: 'forever',
    description: 'For individuals getting started',
    features: [
      '5 AI generations / month',
      '3 active documents',
      'Basic templates',
      '1 GB storage',
      'Community support',
    ],
    cta: 'Current plan',
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 19,
    period: 'month',
    description: 'For professionals and freelancers',
    features: [
      '2,000 AI credits / month',
      'Unlimited documents',
      'Premium templates + Brand Kit',
      '10 GB storage',
      'Priority support',
      'Export to PDF, PPTX, DOCX',
    ],
    current: true,
    popular: true,
    cta: 'Manage plan',
  },
  {
    id: 'team',
    name: 'Team',
    price: 49,
    period: 'month',
    description: 'For teams collaborating together',
    features: [
      '10,000 AI credits / month',
      'Unlimited everything',
      'Real-time collaboration',
      '100 GB shared storage',
      'SSO + advanced security',
      'Dedicated success manager',
    ],
    cta: 'Upgrade to Team',
  },
];

export const invoices: InvoiceItem[] = [
  {
    id: 'inv_2026_07',
    date: '2026-07-01',
    amount: 19,
    status: 'paid',
    description: 'Pro plan — monthly',
  },
  {
    id: 'inv_2026_06',
    date: '2026-06-01',
    amount: 19,
    status: 'paid',
    description: 'Pro plan — monthly',
  },
  {
    id: 'inv_2026_05',
    date: '2026-05-01',
    amount: 19,
    status: 'paid',
    description: 'Pro plan — monthly',
  },
  {
    id: 'inv_2026_08',
    date: '2026-08-01',
    amount: 19,
    status: 'pending',
    description: 'Pro plan — monthly',
  },
];

export const defaultBrandKit: BrandKit = {
  companyName: 'Helio Labs',
  logoUrl: null,
  primaryColor: '#2563EB',
  secondaryColor: '#7C3AED',
  accentColor: '#0EA5E9',
  fonts: { heading: 'Plus Jakarta Sans', body: 'Inter' },
};

export const testimonials = [
  {
    name: 'Sofia Reyes',
    role: 'Head of Design, Lumina',
    avatar: 'https://i.pravatar.cc/150?img=5',
    quote:
      'DocumentOS replaced three tools for our team. The AI generator produces decks that genuinely impress our clients — in a fraction of the time.',
  },
  {
    name: 'Marcus Chen',
    role: 'Founder, Northwind',
    avatar: 'https://i.pravatar.cc/150?img=15',
    quote:
      'I wrote a full investor business plan in an afternoon. The brand kit kept everything on-brand without me lifting a finger.',
  },
  {
    name: 'Priya Nair',
    role: 'Product Manager, Vertex',
    avatar: 'https://i.pravatar.cc/150?img=32',
    quote:
      'The visual editor feels like Figma but for documents. The AI assistant rewrites and summarizes entire sections instantly.',
  },
  {
    name: 'David Okafor',
    role: 'Consultant, Apex',
    avatar: 'https://i.pravatar.cc/150?img=22',
    quote:
      'Proposals that used to take a full day now take an hour. The template marketplace has everything I need.',
  },
];

export const faqs = [
  {
    q: 'How does the AI document generation work?',
    a: 'Describe what you want in plain language. DocumentOS AI drafts a complete, editable document — structure, copy, charts, and design — in seconds. Refine anything with the visual editor or AI assistant.',
  },
  {
    q: 'Can I use my own brand colors and logo?',
    a: 'Yes. The Brand Kit applies your logo, colors, and fonts across every document automatically. Pro and Team plans include full brand kit access.',
  },
  {
    q: 'What formats can I export to?',
    a: 'Export to PDF, PPTX, DOCX, and PNG. Presentations can be presented full-screen directly from the editor. Pro plans unlock all export formats.',
  },
  {
    q: 'Is there a free plan?',
    a: 'Yes. The Free plan includes 5 AI generations per month and 3 active documents — no credit card required. Upgrade anytime.',
  },
  {
    q: 'Can my team collaborate in real time?',
    a: 'The Team plan supports real-time multiplayer editing, shared brand kits, comments, and granular permissions.',
  },
];

export const trustedCompanies = [
  'Lumina',
  'Northwind',
  'Vertex',
  'Apex',
  'Helio',
  'Quanta',
];
